name: build-page-with-doc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#   schedule:
#     - cron: '30 1 * * *'

jobs:
  build-jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout pypose/pypose.github.io
      - uses: ruby/setup-ruby@v1
        name: Setup Ruby
        with:
          # Automatically versioned with .ruby-version
          bundler-cache: true
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 9.8.0
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable # per suggestion of actions/setup-node
        name: Setup Yarn
      - run: make build_deploy
        name: Build Jekyll site
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          token: ${{ secrets.BOT_GH_PAT }}
          branch: gh-pages
          folder: _site
