name: build-page-with-doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout pypose/pypose.github.io
      - uses: actions/cache@v2
        name: Restore dependent gems
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        name: Build Jekyll
        with:
          token: ${{ secrets.JEKYLL_PAT }}
          target_branch: 'gh-pages'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.JEKYLL_PAT}}
          # Required, workflow file name or ID
          workflow: build-sphinx-html
          # Optional, will use the branch
          branch: build-doc
          name: DocumentationHTML
          # Optional, directory where to extract artifact. Defaults to the artifact name (see `name` input)
          path: extract_here
          # Optional, defaults to current repo
          repo: pypose/pypose.github.io
      - name: Display structure of downloaded files
        run: ls -R
