name: build-page-with-doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout pypose/pypose
        with:
          repository: pypose/pypose
          ref: docs
          token: ${{ secrets.JEKYLL_PAT }}
      - uses: ammaraskar/sphinx-action@master
        name: Build Sphinx documentation
        with:
          docs-folder: "docs/"
      - uses: actions/upload-artifact@v1
        name: Save html artifacts
        with:
          name: DocumentationHTML
          path: docs/build/html

  build-jekyll:
    runs-on: ubuntu-latest
    needs: build-sphinx
    steps:
      - uses: actions/checkout@v2
        name: Checkout pypose/pypose.github.io
      - name: Download built documentation
        uses: actions/download-artifact@v2
        with:
          name: DocumentationHTML
          path: docs
      - uses: actions/cache@v2
        name: Restore dependent gems
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        name: Build Jekyll
        with:
          token: ${{ secrets.JEKYLL_PAT }}
          target_branch: 'gh-pages'
      - run: git status --ignored
