name: build-page-with-doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout pypose/pypose.github.io
      - uses: actions/cache@v2
        name: Restore dependent gems
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        name: Build Jekyll
        with:
          token: ${{ secrets.JEKYLL_PAT }}
          target_branch: 'gh-pages'

      - uses: actions/download-artifact@v2
        with:
          name: DocumentationHTML
      - name: Display structure of downloaded files
        run: ls -R
